Rapport des sites (html)
=========================================================================================

Répartition des sites par statut de protection et par type d'espaces protégés.
----------------------------------------------------------------------------------

Ce rapport au format html permet de présenter les résultats en utilisant la célèbre librairie de statistique R.

```{r, echo=F}
opts_chunk$set(fig.width=12, fig.height=8)
library("ggplot2")
library("reshape2")
```

Liste des sites.
-------------------------------------------------------------------------------------------------------

```{r, echo=F}
Data <- data.frame(befref.area[c('name', 'espace')])
colnames(Data)<-c("Nom", "Type")
Data
```

Site par type de statut de protection.
--------------------------------------

```{r, echo=F}
Data <- data.frame(befref.area[c('name', 'espace')])
colnames(Data)<-c("Site", "Type")
ggplot(Data, aes(x=Site))+
  geom_bar(fill="darkblue")+
  labs(title="Status de protection")+
  theme(axis.line=element_blank(),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        axis.title.x = element_text(face="bold", colour="#990000", size=20),
        axis.text.x  = element_text(angle=90, vjust=0.5, size=10))
```


Cartographie des sites.
-----------------------
```{r, echo=F}
plot(befref.area['id'], col=rainbow(25,alpha=0.35))
```

