%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Portrait de la Biodiversité
% Modèle LaTeX
% Version 1.0 (05/11/14)
%
% Auteur Original:
% Pascal Obstétar (pascal.obstetar@gmail.com)
%
% Licence:
% CC BY-NC-SA 3.0 (http://creativecommons.org/licenses/by-nc-sa/3.0/)
% 
% Ce modèle utilise un nombre important de paquet pour optimiser la
% compilation. Il est fortement recommandé de mettre à jour votre version
% LaTex pour ne pas avoir des erreurs de compilation.
%
% Note importante :
% Les images des chapitre doivent avoir un ratio 2:1 largeur:hauteur,
% ie 920px de large et 460px de haut par exemple.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%----------------------------------------------------------------------------------------
%	PAQUETS ET AUTRES CONFIGURATIONS
%----------------------------------------------------------------------------------------

% arara: pdflatex
% arara: makeglossaries
% arara: pdflatex    
% arara: pdflatex

\documentclass[11pt,fleqn]{book} % Police par défaut, taille et justification à droite

\usepackage[top=3cm,bottom=3cm,left=2cm,right=2cm,headsep=10pt,a4paper]{geometry} % Marge des pages

\usepackage{xcolor} % Requis pour spécifier les couleurs par leur nom
\definecolor{ocre}{RGB}{196,55,44} % Definie la couleur ocre de mise en évidence du document
\definecolor{NatureFrance}{RGB}{128,204,40} % Definie la couleur nature france
\definecolor{biodiversite}{RGB}{194,100,0} % Definie la couleur
\definecolor{mosaique}{RGB}{128,204,40} % Definie la couleur
\definecolor{sol}{RGB}{196,55,44} % Definie la couleur
\definecolor{artificiel}{RGB}{148,148,147} % Definie la couleur
\definecolor{agricole}{RGB}{123,94,153} % Definie la couleur
\definecolor{forestier}{RGB}{53,91,35} % Definie la couleur
\definecolor{humide}{RGB}{0,86,151} % Definie la couleur
\definecolor{mer}{RGB}{0,136,152} % Definie la couleur
\definecolor{montagne}{RGB}{137,109,69} % Definie la couleur
\definecolor{particulier}{RGB}{196,55,44} % Definie la couleur
\definecolor{remarquable}{RGB}{194,100,0} % Definie la couleur
\definecolor{espece}{RGB}{112,130,39} % Definie la couleur

% Paramètres de la police
\usepackage{avant} % Utilise la police Avantgarde pour l'entête
%\usepackage{times} % Utilise la police Times pour l'entête
\usepackage{mathptmx} % Utilise la police Adobe Times Roman comme police
% par défaut du texte

\usepackage{microtype} % Modifie légèrement l'espacement dans la police
\usepackage[utf8]{inputenc} % Requis pour la langue française et la gestion des accents
\usepackage[T1]{fontenc} % Utilise l'encodage 8-bit

\usepackage{float} % Permet de forcer l'emplacement des figures, tables...
\restylefloat{table} % Force l'emplacement des tables
\usepackage{colortbl} % Permet de colorer les cellules dans un tableau

\usepackage{calc} % utilisé pour calculer l'espacement automatiquement
% entre les mots et les lettres

\usepackage{multicol} % Permet d'écrire sur plusieurs colonnes dans un tableau
\usepackage{multirow} % Permet d'écrire sur plusieurs lignes dans un tableau
\usepackage{array,makecell} % Permet d'écrire sur plusieurs lignes dans un tableau
\usepackage[tikz]{bclogo} % Permet d'afficher des boîtes originales
%\usepackage{lettrine} % Permet de réaliser des lettrines

%----------------------------------------------------------------------------------------

\usepackage{structure} % Insert le fichier structure.sty contenant la majorité
% de la strucuture du modèle portrait de la biodiversité

% Index et glossaire
\makeindex % Indique à LaTeX de créer les fichiers requis pour les index
\makeglossaries % Indique à LaTeX de créer les fichiers requis pour le glossaire

% Sommaire
\renewcommand{\glossaryname}{Glossaire} % Renomme Glossary en Glossaire

% Image
\usepackage{sidecap} % Permet de mettre les captions à côté de l'image
\graphicspath{{images/}}

%----------------------------------------------------------------------------------------
%  DÉCLARATION DES VARIABLES
%----------------------------------------------------------------------------------------

<<Variables, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
opts_chunk$set(concordance=T,include=T,tidy=F, warning=F, comment=F, error=F)
library(ggplot2)
library(plyr)
library(reshape2)
library(gridExtra)
library(xtable)
commune <- gsub("[(-),0-9]", "", portrait.pdf$commune)
postal <- gsub("[A-Z]", "", portrait.pdf$commune)
id <- portrait.pdf$id
page2 <- portrait.pdf$page2
page3 <- portrait.pdf$page3
page4_1 <- portrait.pdf$page4_1
page4_2 <- portrait.pdf$page4_2
page5_1 <- portrait.pdf$page5_1
page5_2 <- portrait.pdf$page5_2
page7 <- portrait.pdf$page7
page8 <- portrait.pdf$page8
page9 <- portrait.pdf$page9
page10 <- portrait.pdf$page10
page11 <- portrait.pdf$page11
page12 <- portrait.pdf$page12
page13 <- portrait.pdf$page13
page14 <- portrait.pdf$page14
page15 <- portrait.pdf$page15
page16 <- portrait.pdf$page16
page17 <- portrait.pdf$page17
page18 <- portrait.pdf$page18
page19 <- portrait.pdf$page19
page20 <- portrait.pdf$page20
page21 <- portrait.pdf$page21
page22 <- portrait.pdf$page22
page24 <- portrait.pdf$page24
page26 <- portrait.pdf$page26
page28 <- portrait.pdf$page28
page30 <- portrait.pdf$page30
page32 <- portrait.pdf$page32
page33 <- portrait.pdf$page33
page34 <- portrait.pdf$page34
page35 <- portrait.pdf$page35
page36 <- portrait.pdf$page36
page37 <- portrait.pdf$page37
page38 <- portrait.pdf$page38
page40 <- portrait.pdf$page40
page41 <- portrait.pdf$page41
page42 <- portrait.pdf$page42
page43 <- portrait.pdf$page43
page44 <- portrait.pdf$page44
page45 <- portrait.pdf$page45
page46 <- portrait.pdf$page46
page48 <- portrait.pdf$page48
page49 <- portrait.pdf$page49
page50 <- portrait.pdf$page50
page51 <- portrait.pdf$page51
page52 <- portrait.pdf$page52
page53 <- portrait.pdf$page53
page54 <- portrait.pdf$page54
page56 <- portrait.pdf$page56
page57 <- portrait.pdf$page57
page58 <- portrait.pdf$page58
page59 <- portrait.pdf$page59
page60 <- portrait.pdf$page60
page62 <- portrait.pdf$page62
page87 <- portrait.pdf$page87
@

%----------------------------------------------------------------------------------------
%  DÉCLARATION DES ACRONYM
%----------------------------------------------------------------------------------------

\newglossaryentry{points chauds}{name={points chauds}, description={Ce sont des points chauds}}
\newglossaryentry{Natura 2000}{name={Natura 2000}, description={C'est Natura 2000}}
\newglossaryentry{communautaire}{name={communautaire}, description={C'est communautaire}}
\newglossaryentry{ecosystemes}{name={ecosystemes}, description={Ce sont des milieux}}
\newglossaryentry{biotope}{name={biotope}, description={Ce sont des lieux de vie}}
\newglossaryentry{biocenose}{name={biocénose}, description={Ce sont les êtres vivants}}
\newglossaryentry{paysage}{name={paysage}, description={Ce sont des paysages}}


%----------------------------------------------------------------------------------------
%	DÉBUT DU DOCUMENT
%----------------------------------------------------------------------------------------

\begin{document}

%Sweaveinput{AnotherFile.Rnw} : Inclusion d'un autre fichier . Analogue à la commande Latex \input ou \include

%----------------------------------------------------------------------------------------
%	PAGE DE TITRE
%----------------------------------------------------------------------------------------
\begingroup
\AddToShipoutPicture*{\put(0,0){\includegraphics[scale=1]{background}}} % Image d'arrière plan (background)
\par\normalfont\fontsize{40}{45}\sffamily\selectfont
\noindent\textcolor{NatureFrance}{Commune de}\par % Commune de
\par\hspace{1.5cm}\textcolor{NatureFrance}{\Sexpr{commune}}\par % Nom de la commune
\par\hspace{2cm}\textcolor{NatureFrance}{\Sexpr{postal}}\par % Code postal de la commune
\vspace*{10cm}
\par\normalfont\fontsize{25}{30}\sffamily\selectfont
\textcolor{white}{Portrait de la}\par % Portrait de la
\par\normalfont\fontsize{55}{60}\sffamily\selectfont
\textcolor{NatureFrance}{Biodiversité}\par % Biodiversité
\begin{flushright}
\textcolor{white}{Communale}\par % Communale
\end{flushright}
\rfoot{\normalfont\fontsize{20}{10}\sffamily\selectfont\textcolor{white}\today} % Date du jour au format Jour Mois Année
\endgroup

%----------------------------------------------------------------------------------------
%	ÉDITORIAL
%----------------------------------------------------------------------------------------
\cleardoublepage % Force l'édito à démarrer sur une page de droite
\thispagestyle{plain} % Style plain pour cette page
\bgimgedit % Image de fond (../Image/presentation.pdf)
\addcontentsline{toc}{chapter}{Éditorial}
\begingroup
\par\normalfont\fontsize{25}{30}\sffamily\selectfont
\begin{center}
\noindent\textcolor{ocre}{Éditorial}\par % Éditorial
\end{center}
\endgroup
\Sexpr{page3} % texte de l'éditorial de la page 3

%----------------------------------------------------------------------------------------
%	SOMMAIRE
%----------------------------------------------------------------------------------------
\renewcommand{\contentsname}{Sommaire} % Renomme Table des matières en Sommaire
\setcounter{tocdepth}{0} % Niveau chapitre pour le sommaire
\thispagestyle{plain} % Style plain pour cette page
\chapterimage{chapter_sommaire.pdf} % Image vide du sommaire
\tableofcontents % Crée le sommaire

\cleardoublepage % Force le sommaire à commencer sur une page de droite

\pagestyle{fancy} % Entête

%----------------------------------------------------------------------------------------
%	LA BIODIVERSITÉ SUR VOTRE TERRITOIRE
%----------------------------------------------------------------------------------------
\renewcommand{\figurename}{Source} % Change l'intitulé des figures

<<Biodiversite8, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
page8_chapo <- portrait.page8$page_chapo
page8_msg1 <- portrait.page8$page_msg1
page8_msg2 <- portrait.page8$page_msg2
page8_msg3 <- portrait.page8$page_msg3
page8_msg4 <- portrait.page8$page_msg4
page8_loin <- portrait.page8$page_loin
page8_geste <- portrait.page8$page_geste
page8_chiffre <- portrait.page8$page_chiffre
page8_anec <- portrait.page8$page_anec
@

\ClearShipoutPicture % Supprime les fonds image affiché
\chapterimage{chapter_biodiversite.png} % Image du chapitre introduction
\chapter{\textcolor{biodiversite}{La Biodiversité sur votre territoire}}

\includegraphics[scale=0.5]{portrait_page7_\Sexpr{page7}_page7_01_map.png}
\vspace*{4cm}
\begin{bclogo}[arrondi=0.4, couleurBord=biodiversite!30, couleur=biodiversite!30, epBarre=0, logo=]{}
\Sexpr{page8_chapo}

\end{bclogo}

%----------------------------------------------------------------------------------------
%	La biodiversité sur votre territoire - La biodiversité et ses multiples facettes...
%----------------------------------------------------------------------------------------

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\ClearShipoutPicture % Supprime les fonds image affiché
\bgBiodiversite % Image de fond
\section{\textcolor{biodiversite}{La biodiversité et ses multiples facettes...}}

\begin{tabular}{lll}
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{}
\includegraphics[width=8cm, height=6cm]{portrait_page8_\Sexpr{page8}_page_photo_map.png}
\end{bclogo}
} \\
\multicolumn{2}{p{10cm}}
{
\Sexpr{page8_msg1}
\Sexpr{page8_msg2}
}
& \multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Quelques chiffres}
\Sexpr{page8_chiffre}
\end{bclogo}
\begin{center}
\includegraphics[width=3cm, height=3cm]{portrait_page8_\Sexpr{page8}_page_dessin_map.png}
\end{center}
} \\
\multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.3, couleurBord=biodiversite!30, epBarre=0, epBord=1, couleur=biodiversite!30, logo=]{Participez à la connaissance !}
\Sexpr{page8_geste}
\end{bclogo}
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Pour aller plus loin}
\Sexpr{page8_loin}
\end{bclogo}
}
&
\multicolumn{2}{p{10cm}}
{\indent
\Sexpr{page8_msg3}
\Sexpr{page8_msg4}
} \\
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Anecdote ou citation}
\Sexpr{page8_anec}
\end{bclogo}
} \\
\end{tabular}

%----------------------------------------------------------------------------------------
%	La biodiversité sur votre territoire - ...sur votre commune
%----------------------------------------------------------------------------------------
<<Biodiversite9, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
foret <- if(exists("forest.forest")){data.frame(forest.forest$rec_name)} else {data.frame("")}
frt <- data.frame(portrait.page9$frt_dom, portrait.page9$frt_ndom, portrait.page9$frt_aut)
@

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\section{\textcolor{biodiversite}{...sur votre commune}}
\begin{figure}[H]
\includegraphics[scale=0.8]{portrait_page9_\Sexpr{page9}_page9_01_map.png}
\begin{tabular}{|*{3}{>{\centering\arraybackslash}m{4.86cm}|}}
\hline
\rowcolor{biodiversite} \multicolumn{2}{|m{10.14cm}|}{\textbf{FORÊTS RELEVANT DU RÉGIME FORESTIER}} & \\
\cline{1-2}
\rowcolor{biodiversite} Forêts domaniales & Forêts communales & \multirow{-2}{*}{\textbf{AUTRES FORÊTS}} \\
\hline
\Sexpr{frt[1,1]} & \Sexpr{frt[1,2]} & \Sexpr{frt[1,3]}\\
\hline
\rowcolor{biodiversite} \multicolumn{3}{|m{15.44cm}|}{\textbf{FORÊTS SUR VOTRE COMMUNE}} \\
\hline
\multicolumn{3}{|c|}{\Sexpr{foret[1,1]}} \\
\hline
\multicolumn{3}{|c|}{\Sexpr{foret[2,1]}} \\
\hline
\multicolumn{3}{|c|}{\Sexpr{foret[3,1]}} \\
\hline
\multicolumn{3}{|c|}{\Sexpr{foret[4,1]}} \\
\hline
\multicolumn{3}{|c|}{\Sexpr{foret[5,1]}} \\
\hline
\end{tabular}
\end{figure}


%----------------------------------------------------------------------------------------
%	La biodiversité sur votre territoire - La biodiversité, en tant que biens et services...
%----------------------------------------------------------------------------------------

<<Biodiversite10, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
page10_chapo <- portrait.page10$page_chapo
page10_msg1 <- portrait.page10$page_msg1
page10_msg2 <- portrait.page10$page_msg2
page10_msg3 <- portrait.page10$page_msg3
page10_msg4 <- portrait.page10$page_msg4
page10_loin <- portrait.page10$page_loin
page10_geste <- portrait.page10$page_geste
page10_chiffre <- portrait.page10$page_chiffre
page10_anec <- portrait.page10$page_anec
@

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\section{\textcolor{biodiversite}{La biodiversité, en tant que biens et services...}}

\begin{tabular}{lll}
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{}
\includegraphics[width=8cm, height=6cm]{portrait_page10_\Sexpr{page10}_page_photo_map.png}
\end{bclogo}
} \\
\multicolumn{2}{p{10cm}}
{
\Sexpr{page10_msg1}
\Sexpr{page10_msg2}
}
& \multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Quelques chiffres}
\Sexpr{page10_chiffre}
\end{bclogo}
\begin{center}
\includegraphics[width=3cm, height=3cm]{portrait_page10_\Sexpr{page10}_page_dessin_map.png}
\end{center}
} \\
\multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.3, couleurBord=biodiversite!30, epBarre=0, epBord=1, couleur=biodiversite!30, logo=]{Limitez votre empreinte !}
\Sexpr{page10_geste}
\end{bclogo}
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Pour aller plus loin}
\Sexpr{page10_loin}
\end{bclogo}
}
&
\multicolumn{2}{p{10cm}}
{\indent
\Sexpr{page10_msg3}
\Sexpr{page10_msg4}
} \\
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Anecdote ou citation}
\Sexpr{page10_anec}
\end{bclogo}
} \\
\end{tabular}

%----------------------------------------------------------------------------------------
%	La biodiversité sur votre territoire - ...sur votre commune
%----------------------------------------------------------------------------------------

<<Biodiversite11, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
ss <- if(exists("carthage.soussecteur")){data.frame(carthage.soussecteur$rec_name)} else {data.frame("")}
eau <- if(exists("carthage.courseau")){data.frame(carthage.courseau$rec_name)} else {data.frame("")}
@

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\section{\textcolor{biodiversite}{...sur votre commune}}
\begin{figure}[H]
\includegraphics[scale=0.8]{portrait_page11_\Sexpr{page11}_page11_01_map.png}
\begin{tabular}{|m{15.44cm}|}
\hline
\rowcolor{biodiversite} \textbf{SOUS SECTEUR CARTHAGE} \\
\hline
\Sexpr{ss[1,1]} \\
\hline
\Sexpr{ss[2,1]} \\
\hline
\Sexpr{ss[3,1]} \\
\hline
\rowcolor{biodiversite} \textbf{COURS D'EAU} \\
\hline
\Sexpr{eau[1,1]} \\
\hline
\Sexpr{eau[2,1]} \\
\hline
\Sexpr{eau[3,1]} \\
\hline
\Sexpr{eau[4,1]} \\
\hline
\Sexpr{eau[5,1]} \\
\hline
\end{tabular}
\end{figure}

%----------------------------------------------------------------------------------------
%	La biodiversité sur votre territoire - Les causes de l’érosion de la biodiversité...
%----------------------------------------------------------------------------------------

<<Biodiversite12, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
page12_chapo <- portrait.page12$page_chapo
page12_msg1 <- portrait.page12$page_msg1
page12_msg2 <- portrait.page12$page_msg2
page12_msg3 <- portrait.page12$page_msg3
page12_msg4 <- portrait.page12$page_msg4
page12_loin <- portrait.page12$page_loin
page12_geste <- portrait.page12$page_geste
page12_chiffre <- portrait.page12$page_chiffre
page12_anec <- portrait.page12$page_anec
@

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\section{\textcolor{biodiversite}{Les causes de l’érosion de la biodiversité...}}

\begin{tabular}{lll}
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{}
\includegraphics[width=8cm, height=6cm]{portrait_page12_\Sexpr{page12}_page_photo_map.png}
\end{bclogo}
} \\
\multicolumn{2}{p{10cm}}
{
\Sexpr{page12_msg1}
\Sexpr{page12_msg2}
}
& \multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Quelques chiffres}
\Sexpr{page12_chiffre}
\end{bclogo}
\begin{center}
\includegraphics[width=3cm, height=3cm]{portrait_page12_\Sexpr{page12}_page_dessin_map.png}
\end{center}
} \\
\multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.3, couleurBord=biodiversite!30, epBarre=0, epBord=1, couleur=biodiversite!30, logo=]{Aidez la biodiversité !}
\Sexpr{page12_geste}
\end{bclogo}
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Pour aller plus loin}
\Sexpr{page12_loin}
\end{bclogo}
}
&
\multicolumn{2}{p{10cm}}
{\indent
\Sexpr{page12_msg3}
\Sexpr{page12_msg4}
} \\
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Anecdote ou citation}
\Sexpr{page12_anec}
\end{bclogo}
} \\
\end{tabular}

%----------------------------------------------------------------------------------------
%	La biodiversité sur votre territoire - ...et comment répondre à l'érosion de la biodiversité
%----------------------------------------------------------------------------------------

<<Biodiversite13, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
page13_chapo <- portrait.page13$page_chapo
page13_msg1 <- portrait.page13$page_msg1
page13_msg2 <- portrait.page13$page_msg2
page13_msg3 <- portrait.page13$page_msg3
page13_msg4 <- portrait.page13$page_msg4
page13_loin <- portrait.page13$page_loin
page13_geste <- portrait.page13$page_geste
page13_chiffre <- portrait.page13$page_chiffre
page13_anec <- portrait.page13$page_anec
@

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\section{\textcolor{biodiversite}{...et comment répondre à l'érosion de la biodiversité}}

\begin{tabular}{lll}
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{}
\includegraphics[width=8cm, height=6cm]{portrait_page13_\Sexpr{page13}_page_photo_map.png}
\end{bclogo}
} \\
\multicolumn{2}{p{10cm}}
{
\Sexpr{page13_msg1}
\Sexpr{page13_msg2}
}
& \multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Quelques chiffres}
\Sexpr{page13_chiffre}
\end{bclogo}
\begin{center}
\includegraphics[width=3cm, height=3cm]{portrait_page13_\Sexpr{page13}_page_dessin_map.png}
\end{center}
} \\
\multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.3, couleurBord=biodiversite!30, epBarre=0, epBord=1, couleur=biodiversite!30, logo=]{Des petits gestes !}
\Sexpr{page13_geste}
\end{bclogo}
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Pour aller plus loin}
\Sexpr{page13_loin}
\end{bclogo}
}
&
\multicolumn{2}{p{10cm}}
{\indent
\Sexpr{page13_msg3}
\Sexpr{page13_msg4}
} \\
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!30, epBarre=0, logo=]{Anecdote ou citation}
\Sexpr{page13_anec}
\end{bclogo}
} \\
\end{tabular}

%----------------------------------------------------------------------------------------
%	La biodiversité sur votre territoire - Clefs de lecture...
%----------------------------------------------------------------------------------------

<<Biodiversite14, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
page14_chapo <- portrait.page14$page_chapo
page14_msg1 <- portrait.page14$page_msg1
page14_msg2 <- portrait.page14$page_msg2
page14_msg3 <- portrait.page14$page_msg3
page14_msg4 <- portrait.page14$page_msg4
page14_loin <- portrait.page14$page_loin
page14_geste <- portrait.page14$page_geste
page14_chiffre <- portrait.page14$page_chiffre
page14_anec <- portrait.page14$page_anec
@

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\ClearShipoutPicture
\renewcommand{\glossaryname}{\textcolor{biodiversite}{Clefs de lecture...}}
\vspace*{3cm}
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!80, epBarre=0, logo=\bcoutil, couleur=biodiversite!80]{}
\Sexpr{page14_msg1}
\end{bclogo}
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!40, epBarre=0, logo=\bcinfo, couleur=biodiversite!40]{}
\Sexpr{page14_msg2}
\end{bclogo}
\begin{bclogo}[arrondi=0.2, couleurBord=biodiversite!20, epBarre=0, logo=\bcbook, couleur=biodiversite!20]{Glossaire}
\printglossary % le glossaire du chapitre
\end{bclogo}

%----------------------------------------------------------------------------------------
%	La biodiversité sur votre territoire - Dernière page de chapitre
%----------------------------------------------------------------------------------------

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\ClearShipoutPicture % Supprime les fonds image affiché
\bgDerBiodiversite % Image de fond
\section*{}

%----------------------------------------------------------------------------------------
%	LA MOSAÏQUE DES MILIEUX PRÉSENTS SUR VOTRE TERRITOIRE
%----------------------------------------------------------------------------------------
<<Biodiversite16, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
page16_chapo <- portrait.page16$page_chapo
page16_msg1 <- portrait.page16$page_msg1
page16_msg2 <- portrait.page16$page_msg2
page16_msg3 <- portrait.page16$page_msg3
page16_msg4 <- portrait.page16$page_msg4
page16_loin <- portrait.page16$page_loin
page16_geste <- portrait.page16$page_geste
page16_chiffre <- portrait.page16$page_chiffre
page16_anec <- portrait.page16$page_anec
@

\chapterimage{chapter_mosaique.png} % Image du chapitre introudction
\chapter{\textcolor{mosaique}{La Mosaïque des milieux présents} \\ \textcolor{mosaique}{sur votre territoire}}

\includegraphics[scale=0.5]{portrait_page15_\Sexpr{page15}_page15_01_map.png}
\vspace*{2cm}
\begin{bclogo}[arrondi=0.4, couleurBord=mosaique!30, couleur=mosaique!30, epBarre=0, logo=]{}
\Sexpr{page16_chapo}

\end{bclogo}

%----------------------------------------------------------------------------------------
%	La mosaïque des milieux présents sur votre territoire - La mosaïque des milieux...
%----------------------------------------------------------------------------------------
\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\ClearShipoutPicture % Supprime les fonds image affiché
\bgMosaique % Image de fond
\section{\textcolor{mosaique}{La mosaïque des milieux...}}

\begin{tabular}{lll}
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{}
\includegraphics[width=8cm, height=6cm]{portrait_page16_\Sexpr{page16}_page_photo_map.png}
\end{bclogo}
} \\
\multicolumn{2}{p{10cm}}
{
\Sexpr{page16_msg1}
\Sexpr{page16_msg2}
}
& \multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{Quelques chiffres}
\Sexpr{page16_chiffre}
\end{bclogo}
\begin{center}
\includegraphics[width=3cm, height=3cm]{portrait_page16_\Sexpr{page16}_page_dessin_map.png}
\end{center}
} \\
\multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.3, couleurBord=mosaique!30, epBarre=0, epBord=1, couleur=mosaique!30, logo=]{Des petits gestes !}
\Sexpr{page16_geste}
\end{bclogo}
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{Pour aller plus loin}
\Sexpr{page16_loin}
\end{bclogo}
}
&
\multicolumn{2}{p{10cm}}
{\indent
\Sexpr{page16_msg3}
\Sexpr{page16_msg4}
} \\
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{Anecdote ou citation}
\Sexpr{page16_anec}
\end{bclogo}
} \\
\end{tabular}

%----------------------------------------------------------------------------------------
%	La mosaïque des milieux présents sur votre territoire - ...sur votre commune
%----------------------------------------------------------------------------------------
<<Biodiversite17, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
clc <- data.frame(portrait.page17$artificial, portrait.page17$agricole, portrait.page17$foret, portrait.page17$marais, portrait.page17$mer)
@

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\section{...sur votre commune}
\begin{figure}[H]
\includegraphics[scale=0.8]{portrait_page17_\Sexpr{page17}_page17_01_map.png}
\begin{tabular}{|*{5}{>{\centering\arraybackslash}m{2.75cm}|}}
\hline
\rowcolor{mosaique} \multicolumn{5}{|m{15.50cm}|}{\textbf{ZONES CORINE LAND COVER}} \\
\hline
\rowcolor{mosaique} Surface artificielle (ha) & Aire agricole (ha) & Forêt et zone naturelle (ha) & Marais et zone humide (ha) & Cours d'eau, mers et océans (ha) \\
\hline
\Sexpr{clc[1,1]} & \Sexpr{clc[1,2]} & \Sexpr{clc[1,3]} & \Sexpr{clc[1,4]} & \Sexpr{clc[1,5]} \\
\hline
\end{tabular}
\end{figure}


%----------------------------------------------------------------------------------------
%  La mosaïque des milieux présents sur votre territoire - La situation générale...
%----------------------------------------------------------------------------------------
<<Biodiversite18, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
page18_chapo <- portrait.page18$page_chapo
page18_msg1 <- portrait.page18$page_msg1
page18_msg2 <- portrait.page18$page_msg2
page18_msg3 <- portrait.page18$page_msg3
page18_msg4 <- portrait.page18$page_msg4
page18_loin <- portrait.page18$page_loin
page18_geste <- portrait.page18$page_geste
page18_chiffre <- portrait.page18$page_chiffre
page18_anec <- portrait.page18$page_anec
@

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\section{\textcolor{mosaique}{La situation générale...}}

\begin{tabular}{lll}
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{}
\includegraphics[width=8cm, height=6cm]{portrait_page18_\Sexpr{page18}_page_photo_map.png}
\end{bclogo}
} \\
\multicolumn{2}{p{10cm}}
{
\Sexpr{page18_msg1}
\Sexpr{page18_msg2}
}
& \multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{Quelques chiffres}
\Sexpr{page18_chiffre}
\end{bclogo}
\begin{center}
\includegraphics[width=3cm, height=3cm]{portrait_page18_\Sexpr{page18}_page_dessin_map.png}
\end{center}
} \\
\multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.3, couleurBord=mosaique!30, epBarre=0, epBord=1, couleur=mosaique!30, logo=]{Des petits gestes !}
\Sexpr{page18_geste}
\end{bclogo}
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{Pour aller plus loin}
\Sexpr{page18_loin}
\end{bclogo}
}
&
\multicolumn{2}{p{10cm}}
{\indent
\Sexpr{page18_msg3}
\Sexpr{page18_msg4}
} \\
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{Anecdote ou citation}
\Sexpr{page18_anec}
\end{bclogo}
} \\
\end{tabular}

%----------------------------------------------------------------------------------------
%	La mosaïque des milieux présents sur votre territoire - ...sur votre commune
%----------------------------------------------------------------------------------------
<<Biodiversite19, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
alt <- data.frame(portrait.page19$zmin, portrait.page19$zmax)
@

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\section{\textcolor{mosaique}{...sur votre commune}}
\begin{figure}[H]
\centering
\begin{tabular}{|c|c|}
\hline
Climat & Relief et Altitude \\
\hline
\includegraphics[scale=0.35]{portrait_page19_\Sexpr{page19}_page19_01_map.png} & \includegraphics[scale=0.35]{portrait_page19_\Sexpr{page19}_page19_02_map.png} \\
\hline
Géologie et Pédologie & Hydrographie \\
\hline
\includegraphics[scale=0.35]{portrait_page19_\Sexpr{page19}_page19_03_map.png} & \includegraphics[scale=0.35]{portrait_page19_\Sexpr{page19}_page19_04_map.png} \\
\hline
\end{tabular}
\begin{tabular}{|*{2}{>{\centering\arraybackslash}m{6.99cm}|}}
\hline
\rowcolor{mosaique} \multicolumn{2}{|m{14.41cm}|}{\textbf{ALTITUDES}} \\
\hline
\rowcolor{mosaique} Altitude minimale (m) & Altitude maximale (m) \\
\hline
\Sexpr{alt[1,1]} & \Sexpr{alt[1,2]} \\
\hline
\end{tabular}
\end{figure}

%----------------------------------------------------------------------------------------
%  La mosaïque des milieux présents sur votre territoire - Prenons un peu de hauteur...
%----------------------------------------------------------------------------------------
<<Biodiversite20, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
page20_chapo <- portrait.page20$page_chapo
page20_msg1 <- portrait.page20$page_msg1
page20_msg2 <- portrait.page20$page_msg2
page20_msg3 <- portrait.page20$page_msg3
page20_msg4 <- portrait.page20$page_msg4
page20_loin <- portrait.page20$page_loin
page20_geste <- portrait.page20$page_geste
page20_chiffre <- portrait.page20$page_chiffre
page20_anec <- portrait.page20$page_anec
@
\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\section{\textcolor{mosaique}{Prenons un peu de hauteur...}}

\begin{tabular}{lll}
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{}
\includegraphics[width=8cm, height=6cm]{portrait_page20_\Sexpr{page20}_page_photo_map.png}
\end{bclogo}
} \\
\multicolumn{2}{p{10cm}}
{
\Sexpr{page20_msg1}
\Sexpr{page20_msg2}
}
& \multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{Quelques chiffres}
\Sexpr{page20_chiffre}
\end{bclogo}
\begin{center}
\includegraphics[width=3cm, height=3cm]{portrait_page20_\Sexpr{page20}_page_dessin_map.png}
\end{center}
} \\
\multicolumn{1}{p{5cm}}
{\indent
\begin{bclogo}[arrondi=0.3, couleurBord=mosaique!30, epBarre=0, epBord=1, couleur=mosaique!30, logo=]{Des petits gestes !}
\Sexpr{page20_geste}
\end{bclogo}
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{Pour aller plus loin}
\Sexpr{page20_loin}
\end{bclogo}
}
&
\multicolumn{2}{p{10cm}}
{\indent
\Sexpr{page20_msg3}
\Sexpr{page20_msg4}
} \\
\multicolumn{3}{p{16cm}}
{\indent
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!30, epBarre=0, logo=]{Anecdote ou citation}
\Sexpr{page20_anec}
\end{bclogo}
} \\
\end{tabular}


%----------------------------------------------------------------------------------------
%	La mosaïque des milieux présents sur votre territoire - ...au-delà de votre commune
%----------------------------------------------------------------------------------------
<<Biodiversite21, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
greco <- if(exists("portrait.greco")){data.frame(portrait.greco$rec_name)} else {data.frame("")}
ser <- if(exists("portrait.ser")){data.frame(portrait.ser$rec_name)} else {data.frame("")}
serar <- if(exists("portrait.serar")){data.frame(portrait.serar$rec_name)} else {data.frame("")}
her1 <- if(exists("portrait.her1")){data.frame(portrait.her1$rec_name)} else {data.frame("")}
her2 <- if(exists("portrait.her2")){data.frame(portrait.her2$rec_name)} else {data.frame("")}
@

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\section{\textcolor{mosaique}{...au-delà de votre commune}}
\begin{figure}[H]
\centering
\begin{tabular}{|c|c|}
\hline
GRECO & SER \\
\hline
\includegraphics[scale=0.35]{portrait_page21_\Sexpr{page21}_page21_01_map.png} & \includegraphics[scale=0.35]{portrait_page21_\Sexpr{page21}_page21_02_map.png} \\
\hline
SERAR & \\
\hline
& \cellcolor{mosaique} GRECO \\\cline{2-2}
& \Sexpr{greco[1,1]} \\\cline{2-2}
& \Sexpr{greco[2,1]} \\\cline{2-2}
& \cellcolor{mosaique} SER \\\cline{2-2}
& \Sexpr{ser[1,1]} \\\cline{2-2}
& \Sexpr{ser[2,1]} \\\cline{2-2}
& \cellcolor{mosaique} SERAR \\\cline{2-2}
& \Sexpr{serar[1,1]} \\\cline{2-2}
& \Sexpr{serar[2,1]} \\\cline{2-2}
& \cellcolor{mosaique} HER1 \\\cline{2-2}
& \Sexpr{her1[1,1]} \\\cline{2-2}
& \Sexpr{her1[2,1]} \\\cline{2-2}
& \cellcolor{mosaique} HER2 \\\cline{2-2}
& \Sexpr{her2[1,1]} \\\cline{2-2}
\multirow{-15}{*}{\includegraphics[scale=0.35]{portrait_page21_\Sexpr{page21}_page21_03_map.png}} & \Sexpr{her2[2,1]} \\\cline{2-2}
\hline
HER1 & HER2 \\
\hline
\includegraphics[scale=0.35]{portrait_page21_\Sexpr{page21}_page21_04_map.png} & \includegraphics[scale=0.35]{portrait_page21_\Sexpr{page21}_page21_05_map.png} \\
\hline
\end{tabular}
\caption{La mosaïque des milieux au-delà de votre commune}
\end{figure}

%----------------------------------------------------------------------------------------
%  La biodiversité sur votre territoire - Clefs de lecture...
%----------------------------------------------------------------------------------------
<<Biodiversite22, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
page22_chapo <- portrait.page22$page_chapo
page22_msg1 <- portrait.page22$page_msg1
page22_msg2 <- portrait.page22$page_msg2
page22_msg3 <- portrait.page22$page_msg3
page22_msg4 <- portrait.page22$page_msg4
page22_loin <- portrait.page22$page_loin
page22_geste <- portrait.page22$page_geste
page22_chiffre <- portrait.page22$page_chiffre
page22_anec <- portrait.page22$page_anec
@
\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\ClearShipoutPicture
\renewcommand{\glossaryname}{\textcolor{mosaique}{Clefs de lecture...}}
\vspace*{3cm}
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!80, epBarre=0, logo=\bcoutil, couleur=mosaique!80]{}
\Sexpr{page14_msg1}
\end{bclogo}
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!40, epBarre=0, logo=\bcinfo, couleur=mosaique!40]{}
\Sexpr{page14_msg2}
\end{bclogo}
\begin{bclogo}[arrondi=0.2, couleurBord=mosaique!20, epBarre=0, logo=\bcbook, couleur=mosaique!20]{Glossaire}
\printglossary % le glossaire du chapitre
\end{bclogo}

%----------------------------------------------------------------------------------------
%	La mosaïque des milieux présents sur votre territoire - Dernière page de chapitre
%----------------------------------------------------------------------------------------

\newpage % Nouvelle page
\thispagestyle{plain} % Style plain pour cette page
\ClearShipoutPicture % Supprime les fonds image affiché
\bgDerMosaique % Image de fond
\section*{}

% %----------------------------------------------------------------------------------------
% %  LA BIODIVERSITÉ DES SOLS
% %----------------------------------------------------------------------------------------
% 
% \chapterimage{chapter_sols.png} % Image du chapitre introduction
% \chapter{La Biodiversité des sols}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité des sols - Mieux connaître les sols...
% %----------------------------------------------------------------------------------------
% <<Biodiversite24, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page24_chapo <- portrait.page24$page_chapo
% page24_msg1 <- portrait.page24$page_msg1
% page24_msg2 <- portrait.page24$page_msg2
% page24_msg3 <- portrait.page24$page_msg3
% page24_msg4 <- portrait.page24$page_msg4
% page24_loin <- portrait.page24$page_loin
% page24_geste <- portrait.page24$page_geste
% page24_chiffre <- portrait.page24$page_chiffre
% page24_anec <- portrait.page24$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgSols % Image de fond
% \section{Mieux connaître les sols...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page24_\Sexpr{page24}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page24_msg1}
% 
% \Sexpr{page24_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page24_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page24_\Sexpr{page24}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=sol!30, epBarre=0, epBord=1, couleur=sol!30, logo=]{Des petits gestes !}
% \Sexpr{page24_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page24_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page24_msg3}
% 
% \Sexpr{page24_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page24_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %	La Biodiversité des sols - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité des sols - Facteurs d'évolution de la biodiversité des sols...
% %----------------------------------------------------------------------------------------
% <<Biodiversite26, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page26_chapo <- portrait.page26$page_chapo
% page26_msg1 <- portrait.page26$page_msg1
% page26_msg2 <- portrait.page26$page_msg2
% page26_msg3 <- portrait.page26$page_msg3
% page26_msg4 <- portrait.page26$page_msg4
% page26_loin <- portrait.page26$page_loin
% page26_geste <- portrait.page26$page_geste
% page26_chiffre <- portrait.page26$page_chiffre
% page26_anec <- portrait.page26$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Facteurs d'évolution de la biodiversité des sols...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page26_\Sexpr{page26}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page26_msg1}
% 
% \Sexpr{page26_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page26_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page26_\Sexpr{page26}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=sol!30, epBarre=0, epBord=1, couleur=sol!30, logo=]{Des petits gestes !}
% \Sexpr{page26_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page26_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page26_msg3}
% 
% \Sexpr{page26_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page26_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %	La Biodiversité des sols - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité des sols - Message pour la biodiversité des sols...
% %----------------------------------------------------------------------------------------
% <<Biodiversite28, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page28_chapo <- portrait.page28$page_chapo
% page28_msg1 <- portrait.page28$page_msg1
% page28_msg2 <- portrait.page28$page_msg2
% page28_msg3 <- portrait.page28$page_msg3
% page28_msg4 <- portrait.page28$page_msg4
% page28_loin <- portrait.page28$page_loin
% page28_geste <- portrait.page28$page_geste
% page28_chiffre <- portrait.page28$page_chiffre
% page28_anec <- portrait.page28$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Message pour la biodiversité des sols...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page28_\Sexpr{page28}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page28_msg1}
% 
% \Sexpr{page28_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page28_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page28_\Sexpr{page28}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=sol!30, epBarre=0, epBord=1, couleur=sol!30, logo=]{Des petits gestes !}
% \Sexpr{page28_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page28_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page28_msg3}
% 
% \Sexpr{page28_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page28_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %	La Biodiversité des sols - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité des sols - Clefs de lecture...
% %----------------------------------------------------------------------------------------
% <<Biodiversite30, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page30_chapo <- portrait.page30$page_chapo
% page30_msg1 <- portrait.page30$page_msg1
% page30_msg2 <- portrait.page30$page_msg2
% page30_msg3 <- portrait.page30$page_msg3
% page30_msg4 <- portrait.page30$page_msg4
% page30_loin <- portrait.page30$page_loin
% page30_geste <- portrait.page30$page_geste
% page30_chiffre <- portrait.page30$page_chiffre
% page30_anec <- portrait.page30$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Clefs de lecture...}
% 
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!80, epBarre=0, logo=\bcoutil, couleur=sol!80]{}
% \Sexpr{page14_msg1}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!40, epBarre=0, logo=\bcinfo, couleur=sol!40]{}
% \Sexpr{page14_msg2}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=sol!20, epBarre=0, logo=\bcbook, couleur=sol!20]{Glossaire}
% \printglossary % le glossaire du chapitre
% \end{bclogo}
% 
% %----------------------------------------------------------------------------------------
% %	La Biodiversité des sols - Dernière page de chapitre
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgDerSols % Image de fond
% \section*{}
% 
% %----------------------------------------------------------------------------------------
% %  LA BIODIVERSITÉ DANS LES MILIEUX URBANISÉS (URBANISATION, INDUSTRIE...)
% %----------------------------------------------------------------------------------------
% 
% \chapterimage{chapter_artificiel.png} % Image du chapitre introduction
% \chapter{La Biodiversité dans les milieux urbanisés}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux urbanisés (urbanisation, industrie...) - Mieux connaître les milieux artificialisés...
% %----------------------------------------------------------------------------------------
% <<Biodiversite32, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page32_chapo <- portrait.page32$page_chapo
% page32_msg1 <- portrait.page32$page_msg1
% page32_msg2 <- portrait.page32$page_msg2
% page32_msg3 <- portrait.page32$page_msg3
% page32_msg4 <- portrait.page32$page_msg4
% page32_loin <- portrait.page32$page_loin
% page32_geste <- portrait.page32$page_geste
% page32_chiffre <- portrait.page32$page_chiffre
% page32_anec <- portrait.page32$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgArtificiel % Image de fond
% \section{Mieux connaître les milieux artificialisés...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page32_\Sexpr{page32}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page32_msg1}
% 
% \Sexpr{page32_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page32_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page32_\Sexpr{page32}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=artificiel!30, epBarre=0, epBord=1, couleur=artificiel!30, logo=]{Des petits gestes !}
% \Sexpr{page32_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page32_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page32_msg3}
% 
% \Sexpr{page32_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page32_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux urbanisés (urbanisation, industrie...) - ...sur votre commune
% %----------------------------------------------------------------------------------------
% <<Biodiversite33, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% au <- data.frame(portrait.page33$aireurbaine)
% @
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% Part artificialisée & Part non artificialisée \\
% \hline
% \includegraphics[scale=0.35]{portrait_page33_\Sexpr{page33}_page33_01_map.png} & \includegraphics[scale=0.35]{portrait_page33_\Sexpr{page33}_page33_02_map.png} \\
% \hline
% Données carroyées INSEE (200m) & Densité communale \\
% \hline
% \includegraphics[scale=0.35]{portrait_page33_\Sexpr{page33}_page33_03_map.png} & \includegraphics[scale=0.35]{portrait_page33_\Sexpr{page33}_page33_04_map.png} \\
% \hline
% \end{tabular}
% \begin{tabular}{|m{14.44cm}|}
% \hline
% \rowcolor{artificiel}{\textbf{Aires urbaines}} \\
% \hline
% Votre commune fait partie de l'aire urbaine : \Sexpr{au[1,1]} \\
% \hline
% \end{tabular}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux urbanisés (urbanisation, industrie...) - Facteurs d'évolution de la biodiversité en milieux artificialisés...
% %----------------------------------------------------------------------------------------
% <<Biodiversite34, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page34_chapo <- portrait.page34$page_chapo
% page34_msg1 <- portrait.page34$page_msg1
% page34_msg2 <- portrait.page34$page_msg2
% page34_msg3 <- portrait.page34$page_msg3
% page34_msg4 <- portrait.page34$page_msg4
% page34_loin <- portrait.page34$page_loin
% page34_geste <- portrait.page34$page_geste
% page34_chiffre <- portrait.page34$page_chiffre
% page34_anec <- portrait.page34$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgArtificiel % Image de fond
% \section{Mieux connaître les milieux artificialisés...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page34_\Sexpr{page34}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page34_msg1}
% 
% \Sexpr{page34_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page34_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page34_\Sexpr{page34}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=artificiel!30, epBarre=0, epBord=1, couleur=artificiel!30, logo=]{Des petits gestes !}
% \Sexpr{page34_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page34_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page34_msg3}
% 
% \Sexpr{page34_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page34_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %	La Biodiversité dans les milieux urbanisés (urbanisation, industrie...) - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% <<Population, echo=FALSE, size='footnotesize', include=T, fig.pos='h', fig.height=6.5, fig.width=15>>=
% top<-data.frame(subset(portrait.population, com==portrait.portrait$commune)[c(12,3)])
% names(top)[1:2] <- c("Année","Total")
% top <- melt(top, id.vars=c("Année"))
% 
% bottom<-data.frame(subset(portrait.population, com==portrait.portrait$commune)[c(12,10,6,11,8,5,13)])
% names(bottom)[1:7] <- c("Année", "de 0 à 14 ans","de 15 à 29 ans", "de 30 à 44 ans", "de 45 à 59 ans", "de 60 à 74 ans", "75 ans et plus")
% bottom <- melt(bottom, id.vars=c("Année"))
% names(bottom)[1:2] <- c("Année", "Population")
% 
% g.bottom <- ggplot(bottom, aes(x=Année, y=value, fill=Population, ymax=max(value)*1.05)) + geom_bar(stat="identity",
%                   position="dodge", main="Évolution de la taille de la population par classe d'âge", xlab="Année", ylab="Population (nb)") + theme(legend.position="bottom")
% 
% g.top <- ggplot(top, aes(x=Année, y=value, group=variable, ymax=max(value)*1.05)) + geom_line(stat="identity",
%                   position="dodge", main="Évolution de la taille de la population", xlab="Année", ylab="Nb") + geom_line(colour = "red", size=2)
% 
% ## plot graphs and set relative heights
% grid.arrange(g.top,g.bottom, heights = c(2/5, 3/5)) 
% @
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% Tourisme & Pollution lumineuse \\
% \hline
% \includegraphics[scale=0.35]{portrait_page35_\Sexpr{page35}_page35_01_map.png} & \includegraphics[scale=0.35]{portrait_page35_\Sexpr{page35}_page35_02_map.png} \\
% \hline
% \end{tabular}
% \begin{tabular}{|m{14.44cm}|}
% \hline
% \rowcolor{artificiel}{\textbf{Données Atmo}} \\
% \hline
% Les données proviennent de \Sexpr{portrait.atmo$rec_name} située à \Sexpr{portrait.page35$distance} km de \Sexpr{portrait.portrait$rec_name}. \\
% \hline
% \end{tabular}
% \end{figure}
% <<Atmo, echo=FALSE, size='footnotesize', include=T, fig.pos='h', fig.height=6.5, fig.width=15>>=
% atmo<-data.frame(portrait.atmo[c(1,6,4,8,10,12)])
% atmo$j<-365-atmo[1,2]
% names(atmo)[1:7] <- c("Commune", "Indice atmo >= 6", "PM10", "SO2", "O3", "NO2", "Indice atmo < 6")
% right <- melt(atmo[c(1,3,4,5,6)], id.vars=c("Commune"))
% names(right)[2] <- c("Polluants")
% left <- melt(atmo[c(1,2,7)], id.vars=c("Commune"))
% names(left)[2] <- c("Jours")
% 
% left <- ggplot(left, aes(x = "", y=value, fill = Jours)) + labs(title="Indice Atmo", x="", y="") + geom_bar(width = 1, stat="identity") + coord_polar("y", start=0) + theme(legend.position="bottom")
% 
% right <- ggplot(right, aes(x = "", y=value, fill = Polluants)) + labs(title="Polluants", x="", y="") + geom_bar(width = 1, stat="identity") + coord_polar("y", start=0) + theme(legend.position="bottom")
% 
% ## plot graphs and set relative heights
% grid.arrange(left, right, heights = c(1/2, 1/2), ncol=2, nrow=1) 
% @
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux urbanisés (urbanisation, industrie...) - Message pour la biodiversité en milieux artificialisés...
% %----------------------------------------------------------------------------------------
% <<Biodiversite36, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page36_chapo <- portrait.page36$page_chapo
% page36_msg1 <- portrait.page36$page_msg1
% page36_msg2 <- portrait.page36$page_msg2
% page36_msg3 <- portrait.page36$page_msg3
% page36_msg4 <- portrait.page36$page_msg4
% page36_loin <- portrait.page36$page_loin
% page36_geste <- portrait.page36$page_geste
% page36_chiffre <- portrait.page36$page_chiffre
% page36_anec <- portrait.page36$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgArtificiel % Image de fond
% \section{Mieux connaître les milieux artificialisés...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page36_\Sexpr{page36}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page36_msg1}
% 
% \Sexpr{page36_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page36_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page36_\Sexpr{page36}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=artificiel!30, epBarre=0, epBord=1, couleur=artificiel!30, logo=]{Des petits gestes !}
% \Sexpr{page36_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page36_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page36_msg3}
% 
% \Sexpr{page36_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page36_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %	 La Biodiversité dans les milieux urbanisés (urbanisation, industrie...) - ...sur votre commune
% %----------------------------------------------------------------------------------------
% <<Biodiversite37, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% risque <- if(exists("portrait.gaspar_risque")){data.frame(portrait.gaspar_risque$rec_name)} else {data.frame("")}
% names(risque)[1] <- c("Risques")
% sismicite <- if(exists("portrait.gaspar_sismicite")){data.frame(portrait.gaspar_sismicite$rec_name)} else {data.frame("")}
% names(sismicite)[1] <- c("Sismicité")
% papi <- if(exists("portrait.gaspar_commune_papi")){data.frame(portrait.gaspar_commune_papi[c(13,14,6,9,10,11)])} else {data.frame(rbind(sample("", 6, replace = TRUE)))}
% names(papi)[1:6] <- c("Nom du PAPI", "Bassin de risque", "Aléas", "Cours d'eau", "Labellisé le", "Convention signée le")
% dicrim <- if(exists("portrait.gaspar_commune_dicrim")){data.frame(portrait.gaspar_commune_dicrim$dat_publi_dicrim)} else {data.frame("")}
% tim <- if(exists("portrait.gaspar_tim")){data.frame(portrait.gaspar_tim$dat_transmission_tim)} else {data.frame("")}
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% Registre français des émissions polluantes &  Risque sismique \\
% \hline
% \includegraphics[scale=0.35]{portrait_page37_\Sexpr{page37}_page37_01_map.png} & \includegraphics[scale=0.35]{portrait_page37_\Sexpr{page37}_page37_02_map.png} \\
% \hline
% \end{tabular}
% \end{figure}
% 
% \textbf{Information préventive} \\
% La Transmission des Informations au Maire (TIM) a été réalisée par le préfet le \Sexpr{tim} \\
% Le Dossier d'Information Communal des Risques Majeurs (DICRIM) a été arrêté par le maire le \Sexpr{dicrim} \\
% 
% <<Sismicite, echo = FALSE, results = 'asis'>>=  
% print(xtable(sismicite), include.rownames=FALSE, floating=FALSE)
% @
% \vspace{0.3cm}
% <<Risque, echo = FALSE, results = 'asis'>>=  
% print(xtable(risque), include.rownames=FALSE, floating=FALSE)
% @
% \vspace{0.3cm}
% <<PAPI, echo = FALSE, results = 'asis'>>=
% tabli <- xtable(papi)
% align(tabli) <- "|m{0.2\\textwidth}|m{0.2\\textwidth}m{0.1\\textwidth}m{0.05\\textwidth}m{0.3\\textwidth}m{0.12\\textwidth}m{0.12\\textwidth}|"
% print(tabli, include.rownames=FALSE, floating=FALSE)
% @
% \vspace{0.3cm}
% 
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux urbanisés (urbanisation, industrie...) - Clefs de lecture...
% %----------------------------------------------------------------------------------------
% <<Biodiversite38, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page38_chapo <- portrait.page38$page_chapo
% page38_msg1 <- portrait.page38$page_msg1
% page38_msg2 <- portrait.page38$page_msg2
% page38_msg3 <- portrait.page38$page_msg3
% page38_msg4 <- portrait.page38$page_msg4
% page38_loin <- portrait.page38$page_loin
% page38_geste <- portrait.page38$page_geste
% page38_chiffre <- portrait.page38$page_chiffre
% page38_anec <- portrait.page38$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Clefs de lecture...}
% 
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!80, epBarre=0, logo=\bcoutil, couleur=artificiel!80]{}
% \Sexpr{page14_msg1}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!40, epBarre=0, logo=\bcinfo, couleur=artificiel!40]{}
% \Sexpr{page14_msg2}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=artificiel!20, epBarre=0, logo=\bcbook, couleur=artificiel!20]{Glossaire}
% \printglossary % le glossaire du chapitre
% \end{bclogo}
% 
% %----------------------------------------------------------------------------------------
% %	 La Biodiversité dans les milieux urbanisés (urbanisation, industrie...) - Dernière page de chapitre
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgDerArtificiel % Image de fond
% \section*{}
% 
% %----------------------------------------------------------------------------------------
% %  LA BIODIVERSITÉ DANS LES MILIEUX AGRICOLES
% %----------------------------------------------------------------------------------------
% 
% \chapterimage{chapter_agricole.png} % Image du chapitre introduction
% \chapter{La Biodiversité dans les milieux agricoles}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux agricoles - Mieux connaître les milieux agricoles...
% %----------------------------------------------------------------------------------------
% <<Biodiversite40, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page40_chapo <- portrait.page40$page_chapo
% page40_msg1 <- portrait.page40$page_msg1
% page40_msg2 <- portrait.page40$page_msg2
% page40_msg3 <- portrait.page40$page_msg3
% page40_msg4 <- portrait.page40$page_msg4
% page40_loin <- portrait.page40$page_loin
% page40_geste <- portrait.page40$page_geste
% page40_chiffre <- portrait.page40$page_chiffre
% page40_anec <- portrait.page40$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{ Mieux connaître les milieux agricoles...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page40_\Sexpr{page40}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page40_msg1}
% 
% \Sexpr{page40_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page40_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page40_\Sexpr{page40}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=agricole!30, epBarre=0, epBord=1, couleur=agricole!30, logo=]{Des petits gestes !}
% \Sexpr{page40_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page40_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page40_msg3}
% 
% \Sexpr{page40_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page40_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux agricoles - ...sur votre commune
% %----------------------------------------------------------------------------------------
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|}
% \hline
% Carte du registre parcellaire graphique (RPG) \\
% \hline
% \includegraphics[scale=0.35]{portrait_page41_\Sexpr{page41}_page41_01_map.png} \\
% \hline
% \end{tabular}
% \end{figure}
% <<Agreste, echo=FALSE, size='footnotesize', include=T, fig.pos='h', fig.height=12, fig.width=15>>=
% agreste<-data.frame(portrait.agreste[c(1,7,10)])
% names(agreste)[1:3] <- c("Metrique", "Valeur", "Année")
% nb <- subset(agreste, Metrique=="1")
% ut <- subset(agreste, Metrique=="2")
% su <- subset(agreste, Metrique=="3")
% ch <- subset(agreste, Metrique=="4")
% sup <- subset(agreste, Metrique %in% c("5", "6", "7"))
% nb <- ggplot(nb, aes(x=Année, y=Valeur)) + geom_line(color=I("red"), size=2) + labs(title="Exploitations agricoles (NB)", x="", y="") + theme(legend.position="bottom")
% ut <- ggplot(ut, aes(x=Année, y=Valeur)) + geom_line(color=I("blue"), size=2) + labs(title="Travail dans les exploitations (UTA)", x="", y="") + theme(legend.position="bottom")
% su <- ggplot(su, aes(x=Année, y=Valeur)) + geom_line(color=I("green"), size=2) + labs(title="Surface agricole utilisée (HA)", x="", y="") + theme(legend.position="bottom")
% ch <- ggplot(ch, aes(x=Année, y=Valeur)) + geom_line(color=I("orange"), size=2) + labs(title="Cheptel (NB)", x="", y="") + theme(legend.position="bottom")
% sup <- ggplot(sup, aes(x=Année, y=Valeur, fill=Metrique, ymax=max(Valeur)*1.05)) + geom_bar(stat="identity", position="dodge") + ggtitle("5 - Terres labourables, 6 - Cultures permanentes, 7 - Toujours en herbe") + labs(x="Année", y="Superficie (HA)") + theme(legend.position="bottom")
% ## plot graphs
% grid.newpage()
% pushViewport(viewport(layout = grid.layout(3, 2)))
% print(nb, vp = viewport(layout.pos.row = 1, layout.pos.col = 1))
% print(ut, vp = viewport(layout.pos.row = 1, layout.pos.col = 2))
% print(su, vp = viewport(layout.pos.row = 2, layout.pos.col = 1)) 
% print(ch , vp = viewport(layout.pos.row = 2, layout.pos.col = 2)) 
% print(sup, vp = viewport(layout.pos.row = 3, layout.pos.col = 1:2))
% @
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux agricoles - Facteurs d'évolution de la biodiversité en milieux agricoles...
% %----------------------------------------------------------------------------------------
% <<Biodiversite42, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page42_chapo <- portrait.page42$page_chapo
% page42_msg1 <- portrait.page42$page_msg1
% page42_msg2 <- portrait.page42$page_msg2
% page42_msg3 <- portrait.page42$page_msg3
% page42_msg4 <- portrait.page42$page_msg4
% page42_loin <- portrait.page42$page_loin
% page42_geste <- portrait.page42$page_geste
% page42_chiffre <- portrait.page42$page_chiffre
% page42_anec <- portrait.page42$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Facteurs d'évolution de la biodiversité en milieux agricoles...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page42_\Sexpr{page42}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page42_msg1}
% 
% \Sexpr{page42_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page42_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page42_\Sexpr{page42}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=agricole!30, epBarre=0, epBord=1, couleur=agricole!30, logo=]{Des petits gestes !}
% \Sexpr{page42_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page42_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page42_msg3}
% 
% \Sexpr{page42_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page42_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux agricoles - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% Zones en cultures pérennes (RPG) & Zones en jachères (RPG) \\
% \hline
% \includegraphics[scale=0.35]{portrait_page43_\Sexpr{page43}_page43_01_map.png} & \includegraphics[scale=0.35]{portrait_page43_\Sexpr{page43}_page43_02_map.png} \\
% \hline
% Zones en prairies (RPG) & Zones en céréales (RPG) \\
% \hline
% \includegraphics[scale=0.35]{portrait_page43_\Sexpr{page43}_page43_03_map.png} & \includegraphics[scale=0.35]{portrait_page43_\Sexpr{page43}_page43_04_map.png} \\
% \hline
% \end{tabular}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux agricoles - Message pour la biodiversité en milieux agricoles...
% %----------------------------------------------------------------------------------------
% <<Biodiversite44, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page44_chapo <- portrait.page44$page_chapo
% page44_msg1 <- portrait.page44$page_msg1
% page44_msg2 <- portrait.page44$page_msg2
% page44_msg3 <- portrait.page44$page_msg3
% page44_msg4 <- portrait.page44$page_msg4
% page44_loin <- portrait.page44$page_loin
% page44_geste <- portrait.page44$page_geste
% page44_chiffre <- portrait.page44$page_chiffre
% page44_anec <- portrait.page44$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Message pour la biodiversité en milieux agricoles...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page44_\Sexpr{page44}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page44_msg1}
% 
% \Sexpr{page44_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page44_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page44_\Sexpr{page44}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=agricole!30, epBarre=0, epBord=1, couleur=agricole!30, logo=]{Des petits gestes !}
% \Sexpr{page44_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page44_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page44_msg3}
% 
% \Sexpr{page44_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page44_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %	 La Biodiversité dans les milieux agricoles - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% Carte des exploitations Bio & Carte des opérateurs Bio \\
% \hline
% \includegraphics[scale=0.35]{portrait_page45_\Sexpr{page45}_page45_01_map.png} & \includegraphics[scale=0.35]{portrait_page45_\Sexpr{page45}_page45_02_map.png} \\
% \hline
% Carte des surfaces Bio & Carte des cheptels Bio \\
% \hline
% \includegraphics[scale=0.35]{portrait_page45_\Sexpr{page45}_page45_03_map.png} & \includegraphics[scale=0.35]{portrait_page45_\Sexpr{page45}_page45_04_map.png} \\
% \hline
% \end{tabular}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux agricoles - Clefs de lecture...
% %----------------------------------------------------------------------------------------
% <<Biodiversite46, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page46_chapo <- portrait.page46$page_chapo
% page46_msg1 <- portrait.page46$page_msg1
% page46_msg2 <- portrait.page46$page_msg2
% page46_msg3 <- portrait.page46$page_msg3
% page46_msg4 <- portrait.page46$page_msg4
% page46_loin <- portrait.page46$page_loin
% page46_geste <- portrait.page46$page_geste
% page46_chiffre <- portrait.page46$page_chiffre
% page46_anec <- portrait.page46$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Clefs de lecture...}
% 
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!80, epBarre=0, logo=\bcoutil, couleur=agricole!80]{}
% \Sexpr{page14_msg1}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!40, epBarre=0, logo=\bcinfo, couleur=agricole!40]{}
% \Sexpr{page14_msg2}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=agricole!20, epBarre=0, logo=\bcbook, couleur=agricole!20]{Glossaire}
% \printglossary % le glossaire du chapitre
% \end{bclogo}
% 
% %----------------------------------------------------------------------------------------
% %	 La Biodiversité dans les milieux agricoles - Dernière page de chapitre
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgDerAgricole % Image de fond
% \section*{}
% 
% %----------------------------------------------------------------------------------------
% %  LA BIODIVERSITÉ DANS LES MILIEUX FORESTIERS
% %----------------------------------------------------------------------------------------
% 
% \chapterimage{chapter_forestier.png} % Image du chapitre introduction
% \chapter{La Biodiversité dans les milieux forestiers}
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux forestiers - Mieux connaître les milieux forestiers...
% %----------------------------------------------------------------------------------------
% <<Biodiversite48, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page48_chapo <- portrait.page48$page_chapo
% page48_msg1 <- portrait.page48$page_msg1
% page48_msg2 <- portrait.page48$page_msg2
% page48_msg3 <- portrait.page48$page_msg3
% page48_msg4 <- portrait.page48$page_msg4
% page48_loin <- portrait.page48$page_loin
% page48_geste <- portrait.page48$page_geste
% page48_chiffre <- portrait.page48$page_chiffre
% page48_anec <- portrait.page48$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Mieux connaître les milieux forestiers...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page48_\Sexpr{page48}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page48_msg1}
% 
% \Sexpr{page48_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page48_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page48_\Sexpr{page48}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=forestier!30, epBarre=0, epBord=1, couleur=forestier!30, logo=]{Des petits gestes !}
% \Sexpr{page48_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page48_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page48_msg3}
% 
% \Sexpr{page48_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page48_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux forestiers - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% Carte des forêts (CLC) & Carte des formations forestières (IGN) \\
% \hline
% \includegraphics[scale=0.35]{portrait_page49_\Sexpr{page49}_page49_01_map.png} & \includegraphics[scale=0.35]{portrait_page49_\Sexpr{page49}_page49_02_map.png} \\
% \hline
% Carte des SER & Carte des GRECO \\
% \hline
% \includegraphics[scale=0.35]{portrait_page49_\Sexpr{page49}_page49_03_map.png} & \includegraphics[scale=0.35]{portrait_page49_\Sexpr{page49}_page49_04_map.png} \\
% \hline
% \end{tabular}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux forestiers - Facteurs d'évolution de la biodiversité en milieu forestier...
% %----------------------------------------------------------------------------------------
% <<Biodiversite50, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page50_chapo <- portrait.page50$page_chapo
% page50_msg1 <- portrait.page50$page_msg1
% page50_msg2 <- portrait.page50$page_msg2
% page50_msg3 <- portrait.page50$page_msg3
% page50_msg4 <- portrait.page50$page_msg4
% page50_loin <- portrait.page50$page_loin
% page50_geste <- portrait.page50$page_geste
% page50_chiffre <- portrait.page50$page_chiffre
% page50_anec <- portrait.page50$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Facteurs d'évolution de la biodiversité en milieu forestier...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page50_\Sexpr{page50}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page50_msg1}
% 
% \Sexpr{page50_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page50_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page50_\Sexpr{page50}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=forestier!30, epBarre=0, epBord=1, couleur=forestier!30, logo=]{Des petits gestes !}
% \Sexpr{page50_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page50_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page50_msg3}
% 
% \Sexpr{page50_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page50_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux forestiers - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% Carte des arbres vivants & Carte des points (IGN) \\
% \hline
% \includegraphics[scale=0.35]{portrait_page51_\Sexpr{page51}_page51_01_map.png} & \includegraphics[scale=0.35]{portrait_page51_\Sexpr{page51}_page51_02_map.png} \\
% \hline
% \end{tabular}
% \end{figure}
% <<STOC, echo=FALSE, size='footnotesize', include=T, fig.pos='h', fig.height=8, fig.width=15>>=
% stoc<-data.frame(portrait.stoc[c(9,4,8)])
% names(stoc)[1:3] <- c("Espèce", "Valeur", "Année")
% ggplot(stoc, aes(x=Année, y=Valeur)) + geom_line(color=I("red"), size=2, aes(group=Espèce)) + labs(title="Variations de l'indice STOC des espèces des milieux forestiers", x="Année", y="Indice") + theme(legend.position="bottom")
% @
% \vspace{0.3cm}
% <<Espar, echo = FALSE, results = 'asis'>>=  
% espar<-data.frame(ifn.espar[1:10,c(1)])
% names(espar)<-c("Les 10 essences les plus représentées en volume, par ordre décroissant")
% print(xtable(espar), include.rownames=FALSE, floating=FALSE)
% @
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux forestiers - Réponses pour la biodiversité en milieu forestier...
% %----------------------------------------------------------------------------------------
% <<Biodiversite52, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page52_chapo <- portrait.page52$page_chapo
% page52_msg1 <- portrait.page52$page_msg1
% page52_msg2 <- portrait.page52$page_msg2
% page52_msg3 <- portrait.page52$page_msg3
% page52_msg4 <- portrait.page52$page_msg4
% page52_loin <- portrait.page52$page_loin
% page52_geste <- portrait.page52$page_geste
% page52_chiffre <- portrait.page52$page_chiffre
% page52_anec <- portrait.page52$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Réponses pour la biodiversité en milieu forestier...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page52_\Sexpr{page52}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page52_msg1}
% 
% \Sexpr{page52_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page52_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page52_\Sexpr{page52}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=forestier!30, epBarre=0, epBord=1, couleur=forestier!30, logo=]{Des petits gestes !}
% \Sexpr{page52_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page52_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page52_msg3}
% 
% \Sexpr{page52_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page52_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %   La Biodiversité dans les milieux forestiers - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% Carte des forêts publics & Carte des forêts (CLC) \\
% \hline
% \includegraphics[scale=0.35]{portrait_page53_\Sexpr{page53}_page53_01_map.png} & \includegraphics[scale=0.35]{portrait_page53_\Sexpr{page53}_page53_02_map.png} \\
% \hline
% Carte des espaces fragmentés & \\
% \hline
% \includegraphics[scale=0.35]{portrait_page53_\Sexpr{page53}_page53_03_map.png} & \\
% \hline
% \end{tabular}
% \end{figure}
% <<PROMETHEE, echo = FALSE, results = 'asis'>>=
% prome<-if(exists("portrait.promethee")){data.frame(portrait.promethee[c(6,7,11,13,15)])} else {data.frame(rbind(sample("", 5, replace = TRUE)))}
% names(prome)<-c("Lieu-dit", "Surface", "Carreau DFCI", "Année", "Alerte")
% print(xtable(prome), include.rownames=FALSE, floating=FALSE)
% @
% 
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux forestiers - Clefs de lecture...
% %----------------------------------------------------------------------------------------
% <<Biodiversite54, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page54_chapo <- portrait.page54$page_chapo
% page54_msg1 <- portrait.page54$page_msg1
% page54_msg2 <- portrait.page54$page_msg2
% page54_msg3 <- portrait.page54$page_msg3
% page54_msg4 <- portrait.page54$page_msg4
% page54_loin <- portrait.page54$page_loin
% page54_geste <- portrait.page54$page_geste
% page54_chiffre <- portrait.page54$page_chiffre
% page54_anec <- portrait.page54$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Clefs de lecture...}
% 
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!80, epBarre=0, logo=\bcoutil, couleur=forestier!80]{}
% \Sexpr{page14_msg1}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!40, epBarre=0, logo=\bcinfo, couleur=forestier!40]{}
% \Sexpr{page14_msg2}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=forestier!20, epBarre=0, logo=\bcbook, couleur=forestier!20]{Glossaire}
% \printglossary % le glossaire du chapitre
% \end{bclogo}
% 
% %----------------------------------------------------------------------------------------
% %	 La Biodiversité dans les milieux forestiers - Dernière page de chapitre
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgDerForestier % Image de fond
% \section*{}
% 
% %----------------------------------------------------------------------------------------
% %  LA BIODIVERSITÉ DANS LES MILIEUX HUMIDES ET AQUATIQUES
% %----------------------------------------------------------------------------------------
% 
% \chapterimage{chapter_humide.png} % Image du chapitre introduction
% \chapter{La Biodiversité dans les milieux humides \\ et aquatiques}
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux humides - Mieux connaître les milieux humides et aquatiques continentaux...
% %----------------------------------------------------------------------------------------
% <<Biodiversite56, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page56_chapo <- portrait.page56$page_chapo
% page56_msg1 <- portrait.page56$page_msg1
% page56_msg2 <- portrait.page56$page_msg2
% page56_msg3 <- portrait.page56$page_msg3
% page56_msg4 <- portrait.page56$page_msg4
% page56_loin <- portrait.page56$page_loin
% page56_geste <- portrait.page56$page_geste
% page56_chiffre <- portrait.page56$page_chiffre
% page56_anec <- portrait.page56$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Mieux connaître les milieux humides et aquatiques continentaux...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page56_\Sexpr{page56}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page56_msg1}
% 
% \Sexpr{page56_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page56_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page56_\Sexpr{page56}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=humide!30, epBarre=0, epBord=1, couleur=humide!30, logo=]{Des petits gestes !}
% \Sexpr{page56_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page56_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page56_msg3}
% 
% \Sexpr{page56_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page56_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux humides - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% Carte des catégories piscicoles & Carte des états piscicoles \\
% \hline
% \includegraphics[scale=0.35]{portrait_page57_\Sexpr{page57}_page57_01_map.png} & \includegraphics[scale=0.35]{portrait_page57_\Sexpr{page57}_page57_02_map.png} \\
% \hline
% \end{tabular}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux humides - Facteurs d'évolution de la biodiversité en milieu aquatique continental ou humide...
% %----------------------------------------------------------------------------------------
% <<Biodiversite58, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page58_chapo <- portrait.page58$page_chapo
% page58_msg1 <- portrait.page58$page_msg1
% page58_msg2 <- portrait.page58$page_msg2
% page58_msg3 <- portrait.page58$page_msg3
% page58_msg4 <- portrait.page58$page_msg4
% page58_loin <- portrait.page58$page_loin
% page58_geste <- portrait.page58$page_geste
% page58_chiffre <- portrait.page58$page_chiffre
% page58_anec <- portrait.page58$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Facteurs d'évolution de la biodiversité en milieu aquatique continental ou humide...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page58_\Sexpr{page58}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page58_msg1}
% 
% \Sexpr{page58_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page58_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page58_\Sexpr{page58}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=humide!30, epBarre=0, epBord=1, couleur=humide!30, logo=]{Des petits gestes !}
% \Sexpr{page58_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page58_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page58_msg3}
% 
% \Sexpr{page58_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page58_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux humides - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% Carte des catégories piscicoles & Carte des états piscicoles \\
% \hline
% \includegraphics[scale=0.35]{portrait_page59_\Sexpr{page59}_page59_01_map.png} & \includegraphics[scale=0.35]{portrait_page59_\Sexpr{page59}_page59_02_map.png} \\
% \hline
% \end{tabular}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux humides - Réponses pour la biodiversité en milieu aquatique continental ou humide...
% %----------------------------------------------------------------------------------------
% <<Biodiversite60, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page60_chapo <- portrait.page60$page_chapo
% page60_msg1 <- portrait.page60$page_msg1
% page60_msg2 <- portrait.page60$page_msg2
% page60_msg3 <- portrait.page60$page_msg3
% page60_msg4 <- portrait.page60$page_msg4
% page60_loin <- portrait.page60$page_loin
% page60_geste <- portrait.page60$page_geste
% page60_chiffre <- portrait.page60$page_chiffre
% page60_anec <- portrait.page60$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Réponses pour la biodiversité en milieu aquatique continental ou humide...}
% 
% \begin{tabular}{lll}
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{}
% \includegraphics[width=8cm, height=6cm]{portrait_page60_\Sexpr{page60}_page_photo_map.png}
% \end{bclogo}
% } \\
% \multicolumn{2}{p{10cm}}
% {
% \Sexpr{page60_msg1}
% 
% \Sexpr{page60_msg2}
% }
% & \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page60_chiffre}
% \end{bclogo}
% \begin{center}
% \includegraphics[width=3cm, height=3cm]{portrait_page60_\Sexpr{page60}_page_dessin_map.png}
% \end{center}
% } \\
% \multicolumn{1}{p{5cm}}
% {\indent
% \begin{bclogo}[arrondi=0.3, couleurBord=humide!30, epBarre=0, epBord=1, couleur=humide!30, logo=]{Des petits gestes !}
% \Sexpr{page60_geste}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page60_loin}
% \end{bclogo}
% }
% &
% \multicolumn{2}{p{10cm}}
% {\indent
% \Sexpr{page60_msg3}
% 
% \Sexpr{page60_msg4}
% } \\
% \multicolumn{3}{p{16cm}}
% {\indent
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page60_anec}
% \end{bclogo}
% } \\
% \end{tabular}
% 
% %----------------------------------------------------------------------------------------
% %   La Biodiversité dans les milieux humides - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux humides - Clefs de lecture...
% %----------------------------------------------------------------------------------------
% <<Biodiversite62, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% page62_chapo <- portrait.page62$page_chapo
% page62_msg1 <- portrait.page62$page_msg1
% page62_msg2 <- portrait.page62$page_msg2
% page62_msg3 <- portrait.page62$page_msg3
% page62_msg4 <- portrait.page62$page_msg4
% page62_loin <- portrait.page62$page_loin
% page62_geste <- portrait.page62$page_geste
% page62_chiffre <- portrait.page62$page_chiffre
% page62_anec <- portrait.page62$page_anec
% @
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Clefs de lecture...}
% 
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!80, epBarre=0, logo=\bcoutil, couleur=humide!80]{}
% \Sexpr{page14_msg1}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!40, epBarre=0, logo=\bcinfo, couleur=humide!40]{}
% \Sexpr{page14_msg2}
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=humide!20, epBarre=0, logo=\bcbook, couleur=humide!20]{Glossaire}
% \printglossary % le glossaire du chapitre
% \end{bclogo}
% 
% %----------------------------------------------------------------------------------------
% %   La Biodiversité dans les milieux humides - Dernière page de chapitre
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgDerHumide % Image de fond
% \section*{}
% 
% %----------------------------------------------------------------------------------------
% %  LA BIODIVERSITÉ DANS LES MILIEUX MARINS ET LITTORAUX
% %----------------------------------------------------------------------------------------
% 
% \chapterimage{chapter_mer.png} % Image du chapitre introduction
% \chapter{La Biodiversité dans les milieux marins et littoraux}
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux marins et littoraux - Mieux connaître les milieux côtiers...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgMer % Image de fond
% \section{Mieux connaître les milieux côtiers...}
% 
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux marins et littoraux  - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux marins et littoraux  - Facteurs d'évolution de la biodiversité en milieux côtiers...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Facteurs d'évolution de la biodiversité en milieux côtiers...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux marins et littoraux  - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux marins et littoraux  - Message pour la biodiversité en milieux côtiers...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Message pour la biodiversité en milieux côtiers...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %   La Biodiversité dans les milieux marins et littoraux  - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux marins et littoraux  - Clefs de lecture...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Clefs de lecture...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %   La Biodiversité dans les milieux marins et littoraux - Dernière page de chapitre
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgDerMer % Image de fond
% \section*{}
% 
% %----------------------------------------------------------------------------------------
% %  LA BIODIVERSITÉ DANS LES MILIEUX MONTAGNARDS
% %----------------------------------------------------------------------------------------
% 
% \chapterimage{chapter_montagne.png} % Image du chapitre introduction
% \chapter{La Biodiversité dans les milieux montagnards}
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux montagnards - Mieux connaître les milieux montagnards...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgMontagne % Image de fond
% \section{Mieux connaître les milieux montagnards...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux montagnards  - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux montagnards  - Facteurs d'évolution de la biodiversité en milieux montagnards...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Facteurs d'évolution de la biodiversité en milieux montagnards...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux montagnards  - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux montagnards  - Message pour la biodiversité en milieux montagnards...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Message pour la biodiversité en milieux montagnards...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux montagnards - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux montagnards - Clefs de lecture...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Clefs de lecture...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %   La Biodiversité dans les milieux montagnards - Dernière page de chapitre
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgDerMontagne % Image de fond
% \section*{}
% 
% %----------------------------------------------------------------------------------------
% %  LA BIODIVERSITÉ DANS LES MILIEUX PARTICULIERS
% %----------------------------------------------------------------------------------------
% 
% \chapterimage{chapter_particulier.png} % Image du chapitre introduction
% \chapter{La Biodiversité dans les milieux particuliers}
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux particuliers - Mieux connaître les milieux particuliers...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgMosaique % Image de fond
% \section{Mieux connaître les milieux particuliers...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux particuliers  - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux particuliers  - Facteurs d'évolution de la biodiversité en milieux particuliers...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgMosaique % Image de fond
% \section{Facteurs d'évolution de la biodiversité en milieux particuliers...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux particuliers  - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux particuliers  - Message pour la biodiversité en milieux particuliers...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgMosaique % Image de fond
% \section{Message pour la biodiversité en milieux particuliers...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux particuliers - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \lipsum[1-4] % texte
% 
% %----------------------------------------------------------------------------------------
% %  La Biodiversité dans les milieux particuliers - Clefs de lecture...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Clefs de lecture...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %   La Biodiversité dans les milieux particuliers - Dernière page de chapitre
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgDerMosaique % Image de fond
% \section*{}
% 
% %----------------------------------------------------------------------------------------
% %  LES ESPACES NATURELS REMARQUÉS ET MILIEUX PROTÉGÉS
% %----------------------------------------------------------------------------------------
% 
% \chapterimage{chapter_remarquable.png} % Image du chapitre
% \chapter{Les Espaces naturels remarqués \\ et milieux protégés}
% 
% %----------------------------------------------------------------------------------------
% %  Les Espaces naturels remarqués et milieux protégés - Mieux connaître les Les Espaces naturels remarqués...
% %----------------------------------------------------------------------------------------
% 
% <<Biodiversite87, echo=FALSE, warning=F, error=F, comment=F, message=F >>=
% protection <- data.frame(protection.area$rec_name, protection.area$url)
% espace <- data.frame(portrait.page87$espaces_proteges, portrait.page87$znieff_zico, portrait.page87$natura)
% @
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgRemarquable % Image de fond
% \section{Mieux connaître les Les Espaces naturels remarqués...}
% 
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% \Sexpr{page12_chapo}
% \end{bclogo}
% \vspace*{0.3cm}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{}
% Photo
% \end{bclogo}
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% \Sexpr{page12_msg1}
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% \Sexpr{page12_msg2}
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% \Sexpr{page12_msg3}
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% \Sexpr{page12_msg4}
% \end{bclogo}
% \begin{multicols}{2}
% \vfill
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page12_chiffre}
% \end{bclogo}
% \columnbreak
% \vfill
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page12_anec}
% \end{bclogo}
% \end{multicols}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page12_loin}
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% \Sexpr{page12_geste}
% \end{bclogo}
% \vfill
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Dessin}
% \includegraphics[width=3cm, height=3cm]{portrait_page12_\Sexpr{page12}_page_dessin_map.png}
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %  Les Espaces naturels remarqués et milieux protégés - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \includegraphics[scale=0.8]{portrait_page87_\Sexpr{page87}_page87_all_map.png}
% \begin{tabular}{|*{3}{>{\centering\arraybackslash}m{5cm}|}}
% \hline
% \rowcolor{espece} Espaces protégés & ZNIEFF/ZICO & Natura 2000 \\
% \hline
% \Sexpr{espace[1,1]} & \Sexpr{espace[1,2]} & \Sexpr{espace[1,3]}\\
% \hline
% \rowcolor{espece} \multicolumn{2}{|m{10.44cm}|}{Statuts de protection sur votre commune} & Lien URL \\
% \hline
% \multicolumn{2}{|c|}{\Sexpr{protection[1,1]}} & \url{\Sexpr{protection[1,2]}} \\
% \hline
% \multicolumn{2}{|c|}{\Sexpr{protection[2,1]}} & \url{\Sexpr{protection[2,2]}} \\
% \hline
% \multicolumn{2}{|c|}{\Sexpr{protection[3,1]}} & \url{\Sexpr{protection[3,2]}} \\
% \hline
% \multicolumn{2}{|c|}{\Sexpr{protection[4,1]}} & \url{\Sexpr{protection[4,2]}} \\
% \hline
% \multicolumn{2}{|c|}{\Sexpr{protection[5,1]}} & \url{\Sexpr{protection[5,2]}} \\
% \hline
% \end{tabular}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %  Les Espaces naturels remarqués et milieux protégés - Mieux connaître les Les Espaces naturels remarqués...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgRemarquable % Image de fond
% \section{Mieux connaître les Les Espaces naturels remarqués...}
% 
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% \Sexpr{page12_chapo}
% \end{bclogo}
% \vspace*{0.3cm}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{}
% Photo
% \end{bclogo}
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% \Sexpr{page12_msg1}
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% \Sexpr{page12_msg2}
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% \Sexpr{page12_msg3}
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% \Sexpr{page12_msg4}
% \end{bclogo}
% \begin{multicols}{2}
% \vfill
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Quelques chiffres}
% \Sexpr{page12_chiffre}
% \end{bclogo}
% \columnbreak
% \vfill
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Anecdote ou citation}
% \Sexpr{page12_anec}
% \end{bclogo}
% \end{multicols}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% \Sexpr{page12_loin}
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% \Sexpr{page12_geste}
% \end{bclogo}
% \vfill
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Dessin}
% \includegraphics[width=3cm, height=3cm]{portrait_page12_\Sexpr{page12}_page_dessin_map.png}
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %	Les Espaces naturels remarqués et milieux protégés - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% \multicolumn{2}{|c|}{Espaces protégés} \\
% \hline
% RAMSAR - Biosphère & Aire de Protection de Biotope \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_01_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_02_map.png} \\
% \hline
% Parc National & Parc Naturel Marin \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_03_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_04_map.png} \\
% \hline
% Parc Naturel Régional & Réserve Naturelle Régionale \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_05_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_06_map.png} \\
% \hline
% \end{tabular}
% \caption{Espaces protégés}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %	Les Espaces naturels remarqués et milieux protégés - Message pour les milieux protégés...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Message pour les milieux protégés...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %	Les Espaces naturels remarqués et milieux protégés - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% \multicolumn{2}{|c|}{Espaces protégés} \\
% \hline
% Réserve Naturelle Nationale & Réserve Naturelle de Corse \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_07_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_08_map.png} \\
% \hline
% R.N. de Chasse et Faune Sauvage & Conservatoire Du Littoral \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_09_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_12_map.png} \\
% \hline
% Conservatoire d'Espaces Naturels & Réserve Biologique \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_13_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_15_map.png} \\
% \hline
% \end{tabular}
% \caption{Espaces protégés}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %	Les Espaces naturels remarqués et milieux protégés - Message pour les milieux protégés...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Message pour les milieux protégés...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %	Les Espaces naturels remarqués et milieux protégés - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[h]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% \multicolumn{2}{|c|}{Inventaires d'Espaces Naturels} \\
% \hline
% ZNIEFF I et II & ZICO \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_14_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_16_map.png} \\
% \hline
% \multicolumn{2}{|c|}{Natura 2000} \\
% \hline
% Site d'Importance Communautaire & Zone de Protection Spéciale \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_10_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_11_map.png} \\
% \hline
% \end{tabular}
% \caption{Inventaires d'Espaces Naturels et Natura 2000}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %	Les Espaces naturels remarqués et milieux protégés - Dernière page de chapitre
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgDerRemarquable % Image de fond
% \section*{}
% 
% %----------------------------------------------------------------------------------------
% %	DES ESPÈCES SUR VOTRE COMMUNE
% %----------------------------------------------------------------------------------------
% 
% \chapterimage{chapter_espece.png} % Image du chapitre
% \chapter{Des Espèces sur votre commune}
% 
% %----------------------------------------------------------------------------------------
% %	Des espèces sur votre commune - Parlons de la connaissance...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgEspece % Image de fond
% \section{Parlons de la connaissance...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %	Des espèces sur votre commune - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% \multicolumn{2}{|c|}{Espaces protégés} \\
% \hline
% RAMSAR - Biosphère & Aire de Protection de Biotope \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_01_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_02_map.png} \\
% \hline
% Parc National & Parc Naturel Marin \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_03_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_04_map.png} \\
% \hline
% Parc Naturel Régional & Réserve Naturelle Régionale \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_05_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_06_map.png} \\
% \hline
% \end{tabular}
% \caption{Espaces protégés}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %	Des espèces sur votre commune - Parlons des espèces...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Parlons des espèces...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %	Des espèces sur votre commune - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[H]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% \multicolumn{2}{|c|}{Espaces protégés} \\
% \hline
% Réserve Naturelle Nationale & Réserve Naturelle de Corse \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_07_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_08_map.png} \\
% \hline
% R.N. de Chasse et Faune Sauvage & Conservatoire Du Littoral \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_09_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_12_map.png} \\
% \hline
% Conservatoire d'Espaces Naturels & Réserve Biologique \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_13_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_15_map.png} \\
% \hline
% \end{tabular}
% \caption{Espaces protégés}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %	Des espèces sur votre commune - Volet faune - Les mammifères et les oiseaux...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Volet faune - Les mammifères et les oiseaux...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %	Des espèces sur votre commune - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[h]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% \multicolumn{2}{|c|}{Inventaires d'Espaces Naturels} \\
% \hline
% ZNIEFF I et II & ZICO \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_14_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_16_map.png} \\
% \hline
% \multicolumn{2}{|c|}{Natura 2000} \\
% \hline
% Site d'Importance Communautaire & Zone de Protection Spéciale \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_10_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_11_map.png} \\
% \hline
% \end{tabular}
% \caption{Inventaires d'Espaces Naturels et Natura 2000}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %  Des espèces sur votre commune - Volet faune - Les reptiles, les amphibiens et les poissons...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Volet faune - Les reptiles, les amphibiens et les poissons...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %	Des espèces sur votre commune - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[h]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% \multicolumn{2}{|c|}{Inventaires d'Espaces Naturels} \\
% \hline
% ZNIEFF I et II & ZICO \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_14_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_16_map.png} \\
% \hline
% \multicolumn{2}{|c|}{Natura 2000} \\
% \hline
% Site d'Importance Communautaire & Zone de Protection Spéciale \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_10_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_11_map.png} \\
% \hline
% \end{tabular}
% \caption{Inventaires d'Espaces Naturels et Natura 2000}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %  Des espèces sur votre commune - Volet faune - Les arthropodes et les mollusques...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Volet faune - Les arthropodes et les mollusques...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %  Des espèces sur votre commune - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[h]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% \multicolumn{2}{|c|}{Inventaires d'Espaces Naturels} \\
% \hline
% ZNIEFF I et II & ZICO \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_14_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_16_map.png} \\
% \hline
% \multicolumn{2}{|c|}{Natura 2000} \\
% \hline
% Site d'Importance Communautaire & Zone de Protection Spéciale \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_10_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_11_map.png} \\
% \hline
% \end{tabular}
% \caption{Inventaires d'Espaces Naturels et Natura 2000}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %  Des espèces sur votre commune - Volet flore et fonge - Les champignons, les fougères, lichens, algues et mousses...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Volet flore et fonge - Les champignons, les fougères, lichens, algues et mousses...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %	Des espèces sur votre commune - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[h]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% \multicolumn{2}{|c|}{Inventaires d'Espaces Naturels} \\
% \hline
% ZNIEFF I et II & ZICO \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_14_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_16_map.png} \\
% \hline
% \multicolumn{2}{|c|}{Natura 2000} \\
% \hline
% Site d'Importance Communautaire & Zone de Protection Spéciale \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_10_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_11_map.png} \\
% \hline
% \end{tabular}
% \caption{Inventaires d'Espaces Naturels et Natura 2000}
% \end{figure}
% 
% %----------------------------------------------------------------------------------------
% %  Des espèces sur votre commune - Volet flore - Les plantes à graines...
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{Volet flore - Les plantes à graines...}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Introduction}
% Petite introduction
% \end{bclogo}
% \vspace*{0.3cm}
% 
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=]{Photo}
% Petite introduction
% \end{bclogo}
% 
% \begin{multicols}{2}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Message}
% Message
% \end{bclogo}
% \columnbreak
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0, couleurBord=blue!30, epBarre=0, logo=]{Des petits gestes}
% Des petits gestes
% \end{bclogo}
% \end{multicols}
% 
% \begin{multicols}{3}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleurBord=blue!30, epBarre=0, logo=]{Pour aller plus loin}
% Pour aller plus loin
% \end{bclogo}
% \begin{bclogo}[arrondi=0.2, couleur=green!20, couleurBord=blue!30, epBarre=0, logo=\bccrayon]{Photo}
% Petite introduction
% \end{bclogo}
% \end{multicols}
% 
% %----------------------------------------------------------------------------------------
% %	Des espèces sur votre commune - ...sur votre commune
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \section{...sur votre commune}
% \begin{figure}[h]
% \centering
% \begin{tabular}{|c|c|}
% \hline
% \multicolumn{2}{|c|}{Inventaires d'Espaces Naturels} \\
% \hline
% ZNIEFF I et II & ZICO \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_14_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_16_map.png} \\
% \hline
% \multicolumn{2}{|c|}{Natura 2000} \\
% \hline
% Site d'Importance Communautaire & Zone de Protection Spéciale \\
% \hline
% \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_10_map.png} & \includegraphics[scale=0.35]{portrait_page87_\Sexpr{page87}_page87_11_map.png} \\
% \hline
% \end{tabular}
% \caption{Inventaires d'Espaces Naturels et Natura 2000}
% \end{figure}
% 
% 
% %----------------------------------------------------------------------------------------
% %	Des espèces sur votre commune - Dernière page de chapitre
% %----------------------------------------------------------------------------------------
% 
% \newpage % Nouvelle page
% \thispagestyle{plain} % Style plain pour cette page
% \ClearShipoutPicture % Supprime les fonds image affiché
% \bgDerEspece % Image de fond
% \section*{}


%----------------------------------------------------------------------------------------
%	GLOSSAIRE
%----------------------------------------------------------------------------------------

\cleardoublepage
\thispagestyle{plain} % Style plain pour cette page
\chapterimage{chapter_sommaire.pdf} % Image vide
\phantomsection
\setlength{\columnsep}{0.75cm}
\addcontentsline{toc}{chapter}{\textcolor{ocre}{Glossaire}}
\printglossary


%----------------------------------------------------------------------------------------

\end{document}